// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BatchExecute(arg1:Array<main.ServerInfo>,arg2:string):Promise<void>;

export function LoadServers():Promise<Array<main.ServerInfo>>;

export function LoadSettings():Promise<main.GlobalSettings>;

export function SaveServers(arg1:Array<main.ServerInfo>):Promise<void>;

export function SaveSettings(arg1:main.GlobalSettings):Promise<void>;
