// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchExecute(arg1, arg2) {
  return window['go']['main']['App']['BatchExecute'](arg1, arg2);
}

export function LoadServers() {
  return window['go']['main']['App']['LoadServers']();
}

export function SaveServers(arg1) {
  return window['go']['main']['App']['SaveServers'](arg1);
}
